export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_OK = 'FETCH_DATA_OK'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_AUTH_OK = 'USER_AUTH_OK'